INSERT INTO questoes (test, content, year, title, answer_A, answer_B, answer_C, answer_D, answer_E, correct) VALUES 
('VILIBRAS','Informática','2024',
'Qual é a principal finalidade do uso de LIBRAS em ambientes de informática?', 
'Melhorar a velocidade de processamento dos computadores.', 
'Facilitar a comunicação entre surdos e ouvintes.', 
'Aumentar a segurança dos dados armazenados.', 
'Reduzir o consumo de energia dos dispositivos eletrônicos.', 
'Melhorar a qualidade da impressão de documentos.', 
'B'),
('VILIBRAS','Informática','2024',
'Qual tecnologia é frequentemente utilizada para ajudar surdos a se comunicarem através de videochamadas?', 
'Inteligência Artificial.', 
'Reconhecimento Facial.', 
'Tradução Automática de Texto.', 
'Videochamada com Interpretação de LIBRAS.', 
'Realidade Aumentada.', 
'D'),
('VILIBRAS','Informática','2024','Em quais situações o uso de LIBRAS pode ser crucial em um ambiente de TI?', 
'Durante a manutenção de servidores.', 
'No desenvolvimento de software acessível.', 
'Na calibração de impressoras 3D.', 
'No design de placas de circuito impresso.', 
'Na limpeza de hardware.', 
'B'),
('VILIBRAS','Informática','2024','Qual é o termo correto para a tradução simultânea de conteúdo de áudio ou vídeo para LIBRAS em eventos ao vivo?', 
'Subtitulação ao Vivo.', 
'Legendas Ocultas.', 
'Interpretação em LIBRAS.', 
'Transcrição em Tempo Real.', 
'Tradução Simultânea.', 
'C'),
('VILIBRAS','Informática','2024','Qual recurso de acessibilidade pode ser adicionado a um site para ajudar usuários surdos?', 
'Um modo de alta performance.', 
'Um modo de economia de energia.', 
'Uma versão somente texto.', 
'Um avatar que traduz texto para LIBRAS.', 
'Um design responsivo.', 
'D'),
('VILIBRAS','Informática','2024','Qual linguagem de programação tem sido usada para desenvolver ferramentas de tradução automática para LIBRAS?', 
'Java', 
'Python', 
'C++', 
'PHP', 
'Ruby', 
'B'),
('VILIBRAS','Informática','2024','Qual é um dos maiores desafios no desenvolvimento de software que utiliza LIBRAS?', 
'Otimização de desempenho.', 
'Integração com hardware.', 
'Tradução precisa de expressões faciais e corporais.', 
'Redução do consumo de memória.', 
'Compatibilidade com diferentes sistemas operacionais.', 
'C'),
('VILIBRAS','Informática','2024','Qual é a importância de incluir vídeos com interpretação em LIBRAS em conteúdos educacionais online?', 
'Aumentar a visualização dos vídeos.', 
'Melhorar a qualidade de vídeo.', 
'Tornar o conteúdo acessível para surdos.', 
'Reduzir os custos de produção de vídeos.', 
'Facilitar o compartilhamento de vídeos.', 
'C'),
('VILIBRAS','Informática','2024','Que tipo de software pode ser desenvolvido para facilitar a aprendizagem de LIBRAS para programadores?', 
'Editores de texto.', 
'Jogos educativos interativos.', 
'Softwares de antivírus.', 
'Ferramentas de compressão de arquivos.', 
'Softwares de monitoramento de rede.', 
'B'),
('VILIBRAS','Informática','2024','Como as tecnologias de reconhecimento de gestos podem ser aplicadas para melhorar a comunicação em LIBRAS?', 
'Melhorando a resolução de telas.', 
'Acelerando a velocidade de internet.', 
'Traduzindo automaticamente gestos para texto ou voz.', 
'Aumentando a duração da bateria dos dispositivos.', 
'Reduzindo o tamanho dos arquivos de vídeo.', 
'C');